//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressStore
    {
        public int AddressStore_Id { get; set; }
        public int Customer_Id { get; set; }
        public Nullable<int> PostalCode_Id { get; set; }
        public string ContactPerson { get; set; }
        public string Timetable { get; set; }
        public string Phone { get; set; }
        public string FAX { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PostalCode PostalCode { get; set; }
    }
}
