//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressStore
    {
        public int AddressStore_Id { get; set; }
        public int Customer_Id { get; set; }
        public Nullable<int> PostalCode_Id { get; set; }
        public string ContactPerson { get; set; }
        public string Timetable { get; set; }
        public string Phone { get; set; }
        public string FAX { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PostalCode PostalCode { get; set; }
    }
}
