//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BadDebts = new HashSet<BadDebt>();
            this.CustomerOrders = new HashSet<CustomerOrder>();
            this.HistoCustomers = new HashSet<HistoCustomer>();
            this.HistoProviders = new HashSet<HistoProvider>();
            this.ProviderOrders = new HashSet<ProviderOrder>();
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int Bill_Id { get; set; }
        public decimal Year { get; set; }
        public int Serie_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Customer_Alias { get; set; }
        public string Company_Name { get; set; }
        public string Company_Cif { get; set; }
        public string Company_Address { get; set; }
        public Nullable<int> Company_PostalCode_Id { get; set; }
        public string Company_NumProv { get; set; }
        public string DataBank_Bank { get; set; }
        public string DataBank_BankAddress { get; set; }
        public Nullable<int> DataBank_EffectType_Id { get; set; }
        public Nullable<decimal> DataBank_NumEffect { get; set; }
        public Nullable<decimal> DataBank_FirstExpirationData { get; set; }
        public Nullable<decimal> DataBank_ExpirationInterval { get; set; }
        public Nullable<decimal> DataBank_Payday_1 { get; set; }
        public Nullable<decimal> DataBank_Payday_2 { get; set; }
        public Nullable<decimal> DataBank_Payday_3 { get; set; }
        public string DataBank_IBAN_CountryCode { get; set; }
        public string DataBank_IBAN_BankCode { get; set; }
        public string DataBank_IBAN_OfficeCode { get; set; }
        public string DataBank_IBAN_CheckDigits { get; set; }
        public string DataBank_IBAN_AccountNumber { get; set; }
        public Nullable<decimal> BillingData_EarlyPaymentDiscount { get; set; }
        public Nullable<decimal> IVAPercent { get; set; }
        public Nullable<decimal> SurchargePercent { get; set; }
        public Nullable<int> BillingData_Agent_Id { get; set; }
        public Nullable<decimal> BillingData_NumUnpaid { get; set; }
        public string Customer_Remarks { get; set; }
        public string Remarks { get; set; }
        public string FileNamePDF { get; set; }
        public Nullable<bool> Print { get; set; }
        public Nullable<bool> SendByEMail { get; set; }
        public decimal TotalAmount { get; set; }
        public string ExpirationDate { get; set; }
    
        public virtual Agent Agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BadDebt> BadDebts { get; set; }
        public virtual BillingSerie BillingSerie { get; set; }
        public virtual EffectType EffectType { get; set; }
        public virtual PostalCode PostalCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoCustomer> HistoCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoProvider> HistoProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderOrder> ProviderOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
