//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    
    public partial class CustomerOrderMovementsForReport
    {
        public Nullable<int> DeliveryNoteId { get; set; }
        public Nullable<int> BillId { get; set; }
        public int CustomerId { get; set; }
        public string CustomerCompanyName { get; set; }
        public Nullable<int> GoodId { get; set; }
        public string GoodDescription { get; set; }
        public Nullable<decimal> UnitBilling { get; set; }
        public Nullable<decimal> UnitShipping { get; set; }
        public string According { get; set; }
        public string SendType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
