//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderMovement
    {
        public int CustomerOrderMovement_Id { get; set; }
        public Nullable<int> CustomerOrder_Id { get; set; }
        public Nullable<int> Good_Id { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Unit_Shipping { get; set; }
        public Nullable<decimal> Unit_Billing { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> Comission { get; set; }
        public string Remark { get; set; }
        public bool According { get; set; }
        public bool Comi { get; set; }
        public bool Historic { get; set; }
        public string Unit_Shipping_Definition { get; set; }
        public string Unit_Billing_Definition { get; set; }
        public string Internal_Remark { get; set; }
        public Nullable<int> RowOrder { get; set; }
    
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual Good Good { get; set; }
    }
}
