//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    
    public partial class DiaryBandage
    {
        public Nullable<int> Bill_Id { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public int Customer_Id { get; set; }
        public string Company_Name { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> EarlyPayementDiscount { get; set; }
        public Nullable<decimal> TaxableBaseAmount { get; set; }
        public Nullable<decimal> IVAAmount { get; set; }
        public Nullable<decimal> SurchargeAmount { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
