//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    
    public partial class DiaryBandage
    {
        public Nullable<int> Bill_Id { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public int Customer_Id { get; set; }
        public string Company_Name { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> EarlyPayementDiscount { get; set; }
        public Nullable<decimal> TaxableBaseAmount { get; set; }
        public Nullable<decimal> IVAAmount { get; set; }
        public Nullable<decimal> SurchargeAmount { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
