//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoGood
    {
        public int Histo_Id { get; set; }
        public int Good_Id { get; set; }
        public Nullable<decimal> Year { get; set; }
        public Nullable<decimal> Sales_Acum_1 { get; set; }
        public Nullable<decimal> Sales_Acum_2 { get; set; }
        public Nullable<decimal> Sales_Acum_3 { get; set; }
        public Nullable<decimal> Sales_Acum_4 { get; set; }
        public Nullable<decimal> Sales_Acum_5 { get; set; }
        public Nullable<decimal> Sales_Acum_6 { get; set; }
        public Nullable<decimal> Sales_Acum_7 { get; set; }
        public Nullable<decimal> Sales_Acum_8 { get; set; }
        public Nullable<decimal> Sales_Acum_9 { get; set; }
        public Nullable<decimal> Sales_Acum_10 { get; set; }
        public Nullable<decimal> Sales_Acum_11 { get; set; }
        public Nullable<decimal> Sales_Acum_12 { get; set; }
        public Nullable<decimal> Costs_Acum_1 { get; set; }
        public Nullable<decimal> Costs_Acum_2 { get; set; }
        public Nullable<decimal> Costs_Acum_3 { get; set; }
        public Nullable<decimal> Costs_Acum_4 { get; set; }
        public Nullable<decimal> Costs_Acum_5 { get; set; }
        public Nullable<decimal> Costs_Acum_6 { get; set; }
        public Nullable<decimal> Costs_Acum_7 { get; set; }
        public Nullable<decimal> Costs_Acum_8 { get; set; }
        public Nullable<decimal> Costs_Acum_9 { get; set; }
        public Nullable<decimal> Costs_Acum_10 { get; set; }
        public Nullable<decimal> Costs_Acum_11 { get; set; }
        public Nullable<decimal> Costs_Acum_12 { get; set; }
    
        public virtual Good Good { get; set; }
    }
}
