//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoGood
    {
        public int Histo_Id { get; set; }
        public int Good_Id { get; set; }
        public Nullable<decimal> Year { get; set; }
        public Nullable<decimal> Sales_Acum_1 { get; set; }
        public Nullable<decimal> Sales_Acum_2 { get; set; }
        public Nullable<decimal> Sales_Acum_3 { get; set; }
        public Nullable<decimal> Sales_Acum_4 { get; set; }
        public Nullable<decimal> Sales_Acum_5 { get; set; }
        public Nullable<decimal> Sales_Acum_6 { get; set; }
        public Nullable<decimal> Sales_Acum_7 { get; set; }
        public Nullable<decimal> Sales_Acum_8 { get; set; }
        public Nullable<decimal> Sales_Acum_9 { get; set; }
        public Nullable<decimal> Sales_Acum_10 { get; set; }
        public Nullable<decimal> Sales_Acum_11 { get; set; }
        public Nullable<decimal> Sales_Acum_12 { get; set; }
        public Nullable<decimal> Costs_Acum_1 { get; set; }
        public Nullable<decimal> Costs_Acum_2 { get; set; }
        public Nullable<decimal> Costs_Acum_3 { get; set; }
        public Nullable<decimal> Costs_Acum_4 { get; set; }
        public Nullable<decimal> Costs_Acum_5 { get; set; }
        public Nullable<decimal> Costs_Acum_6 { get; set; }
        public Nullable<decimal> Costs_Acum_7 { get; set; }
        public Nullable<decimal> Costs_Acum_8 { get; set; }
        public Nullable<decimal> Costs_Acum_9 { get; set; }
        public Nullable<decimal> Costs_Acum_10 { get; set; }
        public Nullable<decimal> Costs_Acum_11 { get; set; }
        public Nullable<decimal> Costs_Acum_12 { get; set; }
    
        public virtual Good Good { get; set; }
    }
}
