//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lock
    {
        public string TableName { get; set; }
        public string IdRegister { get; set; }
        public int LocalConnection_Id { get; set; }
    
        public virtual LocalConnection LocalConnection { get; set; }
    }
}
