//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public int Parameter_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Address { get; set; }
        public Nullable<int> Company_PostalCode_Id { get; set; }
        public string Company_Phone_1 { get; set; }
        public string Company_Phone_2 { get; set; }
        public string Company_MobilePhone { get; set; }
        public string Company_Fax { get; set; }
        public string Company_EMail { get; set; }
        public string Company_CIF { get; set; }
        public Nullable<decimal> Company_DaysVtoRisk { get; set; }
        public Nullable<decimal> Provider_NumProviderOrder { get; set; }
        public Nullable<decimal> Customer_NumOrder { get; set; }
        public Nullable<decimal> Customer_NumDeliveryNote { get; set; }
        public Nullable<decimal> Customer_NumBill { get; set; }
        public string DataBank_IBAN_CountryCode { get; set; }
        public string DataBank_IBAN_BankCode { get; set; }
        public string DataBank_IBAN_OfficeCode { get; set; }
        public string DataBank_IBAN_CheckDigits { get; set; }
        public string DataBank_IBAN_AccountNumber { get; set; }
        public string DataBank_Bank { get; set; }
        public string DataBank_BankAddress { get; set; }
    
        public virtual PostalCode PostalCode { get; set; }
    }
}
