//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceRange
    {
        public int PriceRange_Id { get; set; }
        public int Good_Id { get; set; }
        public Nullable<decimal> Sequence { get; set; }
        public Nullable<decimal> Since { get; set; }
        public Nullable<decimal> Until { get; set; }
    
        public virtual Good Good { get; set; }
    }
}
