//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceRange
    {
        public int PriceRange_Id { get; set; }
        public int Good_Id { get; set; }
        public Nullable<decimal> Sequence { get; set; }
        public Nullable<decimal> Since { get; set; }
        public Nullable<decimal> Until { get; set; }
    
        public virtual Good Good { get; set; }
    }
}
