//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderOrderMovement
    {
        public int ProviderOrderMovement_Id { get; set; }
        public Nullable<int> ProviderOrder_Id { get; set; }
        public Nullable<int> Good_Id { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Unit_Shipping { get; set; }
        public Nullable<decimal> Unit_Billing { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> Comission { get; set; }
        public string Remark { get; set; }
        public bool According { get; set; }
        public bool Comi { get; set; }
        public bool Historic { get; set; }
        public string Unit_Shipping_Definition { get; set; }
        public string Unit_Billing_Definition { get; set; }
        public string Internal_Remark { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public string ClientName { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual ProviderOrder ProviderOrder { get; set; }
    }
}
