//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.WarehouseMovements = new HashSet<WarehouseMovement>();
        }
    
        public int Provider_Id { get; set; }
        public int Provider_Number { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public string NIF { get; set; }
        public string Address { get; set; }
        public Nullable<int> PostalCode_Id { get; set; }
        public string Phone_1 { get; set; }
        public string Phone_2 { get; set; }
        public string Fax { get; set; }
        public string MobilePhone { get; set; }
        public string EMail { get; set; }
        public string AcountAcounting { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> TransferPercent { get; set; }
        public Nullable<decimal> PromptPaymentDiscount { get; set; }
        public Nullable<decimal> AdditionalDiscount { get; set; }
        public Nullable<int> Agent_Id { get; set; }
        public bool Canceled { get; set; }
    
        public virtual PostalCode PostalCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseMovement> WarehouseMovements { get; set; }
        public virtual Agent Agent { get; set; }
    }
}
