//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.WarehouseMovements = new HashSet<WarehouseMovement>();
            this.HistoProviders = new HashSet<HistoProvider>();
            this.ProviderOrders = new HashSet<ProviderOrder>();
            this.RelatedProviders = new HashSet<RelatedProvider>();
            this.RelatedProviders1 = new HashSet<RelatedProvider>();
        }
    
        public int Provider_Id { get; set; }
        public int Provider_Number { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public string NIF { get; set; }
        public string Address { get; set; }
        public Nullable<int> PostalCode_Id { get; set; }
        public string Phone_1 { get; set; }
        public string Phone_2 { get; set; }
        public string Fax { get; set; }
        public string MobilePhone { get; set; }
        public string EMail { get; set; }
        public string AcountAcounting { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> TransferPercent { get; set; }
        public Nullable<decimal> PromptPaymentDiscount { get; set; }
        public Nullable<decimal> AdditionalDiscount { get; set; }
        public Nullable<int> Agent_Id { get; set; }
        public bool Canceled { get; set; }
        public Nullable<decimal> SeveralData_Acum_1 { get; set; }
        public Nullable<decimal> SeveralData_Acum_2 { get; set; }
        public Nullable<decimal> SeveralData_Acum_3 { get; set; }
        public Nullable<decimal> SeveralData_Acum_4 { get; set; }
        public Nullable<decimal> SeveralData_Acum_5 { get; set; }
        public Nullable<decimal> SeveralData_Acum_6 { get; set; }
        public Nullable<decimal> SeveralData_Acum_7 { get; set; }
        public Nullable<decimal> SeveralData_Acum_8 { get; set; }
        public Nullable<decimal> SeveralData_Acum_9 { get; set; }
        public Nullable<decimal> SeveralData_Acum_10 { get; set; }
        public Nullable<decimal> SeveralData_Acum_11 { get; set; }
        public Nullable<decimal> SeveralData_Acum_12 { get; set; }
        public Nullable<decimal> BillingData_CurrentRisk { get; set; }
    
        public virtual PostalCode PostalCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseMovement> WarehouseMovements { get; set; }
        public virtual Agent Agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoProvider> HistoProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderOrder> ProviderOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedProvider> RelatedProviders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedProvider> RelatedProviders1 { get; set; }
    }
}
