//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    
    public partial class Range
    {
        public string Good_Code { get; set; }
        public string Familia { get; set; }
        public string Good_Description { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_1 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_2 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_3 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_4 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_5 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_6 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_7 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_8 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_9 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_10 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_11 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Retail_Price_12 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_1 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_2 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_3 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_4 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_5 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_6 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_7 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_8 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_9 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_10 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_11 { get; set; }
        public Nullable<decimal> Cumulative_Sales_Cost_12 { get; set; }
    }
}
