//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedProvider
    {
        public int Provider_Id { get; set; }
        public int Provider_Canceled_Id { get; set; }
        public string Remarks { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual Provider Provider1 { get; set; }
    }
}
