//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedProvider
    {
        public int Provider_Id { get; set; }
        public int Provider_Canceled_Id { get; set; }
        public string Remarks { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual Provider Provider1 { get; set; }
    }
}
