//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseMovement
    {
        public int WarehouseMovement_Id { get; set; }
        public int Good_Id { get; set; }
        public Nullable<int> Provider_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount_Unit_Shipping { get; set; }
        public Nullable<decimal> Amount_Unit_Billing { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool According { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
