//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HispaniaComptabilitat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseMovement
    {
        public int WarehouseMovement_Id { get; set; }
        public int Good_Id { get; set; }
        public Nullable<int> Provider_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount_Unit_Shipping { get; set; }
        public Nullable<decimal> Amount_Unit_Billing { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool According { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
